spring:
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:customers
    password: '{cipher}90bfd7a32867597300c8d2476a6452be5420d2d4ab69a3d840811e3151923303'
